version: '3.9'

services:

  postgres:
    hostname: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user_db -d db-highload" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: db-highload
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: highload
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - rdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOO_4LW_COMMANDS_WHITELISTL: ruok
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    healthcheck:
      test: "nc -z localhost 9092 || exit -1"
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  config:
    image: justdan777/config:0.0.1-SNAPSHOT
    ports:
      - "8888:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:8888/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      kafka:
        condition: service_healthy
      postgres:
        condition: service_healthy

  eureka:
    image: justdan777/eureka:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      config:
        condition: service_healthy

  ws:
    image: justdan777/ws:0.0.1-SNAPSHOT
    ports:
      - "6666:6666"
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  notification:
    image: justdan777/notification:0.0.1-SNAPSHOT
    environment:
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
      - KAFKA_BOOTSTRAP_URI=http://kafka:9092
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  file:
    image: justdan777/file:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
      - WS_SERVER_URI=ws://ws:6666/highload-ws
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  user:
    deploy:
      replicas: 3
    image: justdan777/user:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  auth:
    deploy:
      replicas: 1
    image: justdan777/auth:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  translator:
    deploy:
      replicas: 2
    image: justdan777/translator:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
      - KAFKA_BOOTSTRAP_URI=http://kafka:9092
      - WS_SERVER_URI=ws://ws:6666/highload-ws
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  processor:
    deploy:
      replicas: 2
    image: justdan777/processor:0.0.1-SNAPSHOT
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    depends_on:
      eureka:
        condition: service_healthy

  gateway:
    image: justdan777/gateway:0.0.1-SNAPSHOT
    ports:
      - "8765:8765"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - EUREKA_URI=http://eureka:8761/eureka
      - CONFIGSERVER_URI=http://config:8888
    restart: always
    depends_on:
      eureka:
        condition: service_healthy
volumes:
  rdb-data: