### SignIn as user (should be ok)
POST http://localhost:8765/auth/signIn
Content-Type: application/json

{
  "username": "vipvip",
  "password": "V1p-----"
}

### SignIn as admin (should be ok)
POST http://localhost:8765/auth/signIn
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### ZorthCompile with expired JWT (should fail)
POST http://localhost:8765/zorth/compile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5ODMzODE5MiwiZXhwIjoxNjk4MzM5NjMyfQ.gFbzG86VToANpwfqH1SvCLeglCVikgaIUsCAavorgVI

{
  "debug": true,
  "text": "variable p\n3 p\n! p @"
}

### ZorthCompile with valid JWT (should be ok)
POST http://localhost:8765/zorth/compile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDQyMDA0NiwiZXhwIjoxNzAwNDIxNDg2fQ.ZlSN9Ya8VWhs0mpBzn29O_tkQJZ-8H-HKhobeqXpVU8

{
  "debug": true,
  "text": "variable p\n5 p\n! p @"
}

### Get compiler-outs (should be ok)
GET http://localhost:8765/zorth/compiler-outs?request-id=3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aXB2aXAiLCJpYXQiOjE3MDA0MTg3NTYsImV4cCI6MTcwMDQyMDE5Nn0.qbfcQIzDagRTJ5CG0Vn206otVu4Rb5asbT7b3aQfsX8

### Get debug-messages (should be ok)
GET http://localhost:8765/zorth/debug-messages
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDQxNDU1OSwiZXhwIjoxNzAwNDE1OTk5fQ.4Ru6HKNXzcyMtP0sjM9HZOIYFDR4RL_6bS7b9Cj-YWI


### AddUser as user (should fail)
POST http://localhost:8765/user/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5OTczNTQ2NywiZXhwIjoxNjk5NzM2OTA3fQ.zHs2yJJPupxaQ3KcDnyN_Obviz9znuHxKPP5ajNFKA4
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### AddUser as admin (should be ok)
POST http://localhost:8765/user/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDMzMDg1MSwiZXhwIjoxNzAwMzMyMjkxfQ.ATrKvZi82ZdMx9oJMzwdNZI3Y5bri8T_LQ_EjfTFGeA

{
  "username": "vipvip",
  "password": "V1p-----"
}

### AddUser (should fail)
POST http://localhost:8765/user/api/v1/add
Content-Type: application/json
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### ChangeRole as admin (should be ok)
PUT http://localhost:8765/user-service/users/vipvip/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDMzNTYyNCwiZXhwIjoxNzAwMzM3MDY0fQ.DhxbPsQjfgCpUwQyvxKH5ousjrDlS63qzxaAMHMe1yU

{
  "role": "ROLE_VIP"
}

### Get requests of self as vip (should be ok)
GET http://localhost:8765/user-service/users/vipvip/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aXB2aXAiLCJpYXQiOjE3MDAzMzQyOTMsImV4cCI6MTcwMDMzNTczM30._EDt9RjC7aO7wpoGgtcPDjRvzlv9CGxHPKfnh1I4Lw0