### sign-in as vip (should be ok)
POST http://localhost:8765/auth/sign-in
Content-Type: application/json

{
  "username": "vipvip",
  "password": "V1p-----"
}

### sign-in as user (should be ok)
POST http://localhost:8765/auth/sign-in
Content-Type: application/json

{
  "username": "userr",
  "password": "Us3r----"
}

### sign-in as admin (should be ok)
POST http://localhost:8765/auth-service/sign-in
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### ZorthCompile with valid JWT (should be ok)
POST http://localhost:8765/zorth-translator-service/compile-from-file?email=yarusking@mail.ru
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMjkxMTMzMywiZXhwIjoxNzAyOTEyNzczfQ.sDa_3dTPxnyIJ29NPoXHIeLOJnX8vMB8rL8ekdvUEbo

{
  "debug": true,
  "fileId": 3
}

### Get compiler-outs (should be ok)
GET http://localhost:8765/zorth/compiler-outs/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMTI3OTMwMiwiZXhwIjoxNzAxMjgwNzQyfQ.22kiPb9SJaj5UHV6tg3PV5o-C-h__TDFXiIPpBq6Rlc

### Get debug-messages (should be ok)
GET http://localhost:8765/zorth/debug-messages?request-id=11
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMTI3NzM1NywiZXhwIjoxNzAxMjc4Nzk3fQ.cWNqoP3lMBKOvoUQGyVUOZSnc9mxlh1k06qYtdLebWw


### AddUser as user (should fail)
POST http://localhost:8765/user/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5OTczNTQ2NywiZXhwIjoxNjk5NzM2OTA3fQ.zHs2yJJPupxaQ3KcDnyN_Obviz9znuHxKPP5ajNFKA4
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### Add user as admin (should be ok)
POST http://localhost:8765/user-service/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMjE0NTI5MCwiZXhwIjoxNzAyMTQ2NzMwfQ.DLHGVytVTLQpQpbwOemEnt953Q3qy7t58XEOpjmvTcA

{
  "username": "userr",
  "password": "Us3r----"
}

### Add vip as admin (should be ok)
POST http://localhost:8765/user-service/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDg1ODU5NiwiZXhwIjoxNzAwODYwMDM2fQ.58UAlAaMdU8bPUyw43W4468ADuFqZ7N78GK16uC0HrQ

{
  "username": "vipvip",
  "password": "V1p-----"
}

### AddUser (should fail)
POST http://localhost:8765/user/api/v1/add
Content-Type: application/json
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### ChangeRole as admin (should be ok)
PUT http://localhost:8765/user-service/users/vipvip/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyciIsImlhdCI6MTcwMDg2NjE0NiwiZXhwIjoxNzAwODY3NTg2fQ.6KtWCx69S9XI9IrH4jaYEOCPleajqtwdNQGZjW_ozkI

{
  "role": "ROLE_VIP"
}

### Get requests of self as vip (should be ok)
GET http://localhost:8765/user-service/users/vipvip/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aXB2aXAiLCJpYXQiOjE3MDA5MTI5MTEsImV4cCI6MTcwMDkxNDM1MX0.ut7pXTvfyFdcF7lY0AABi634sePkb3OTJqkBPRbHZZc

### Execute
POST http://localhost:8765/zorth/execute
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMTI5NDg0NCwiZXhwIjoxNzAxMjk2Mjg0fQ.9_6wYcp-S1GtWO2uUMwomaZKZIbGJUWQU8KB-8zqvNA

{
  "input": ["k", "2", "3"],
  "requestId": 1
}

### Pipeline
POST http://localhost:8765/zorth/pipeline
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMTgxMzQ0MywiZXhwIjoxNzAxODE0ODgzfQ.GBuwtqUjgpYS7A5-w8Oo5i7o103O2xr4B0Wfj_9V9RY


{
  "debug": true,
  "text": "variable p\n5 p\n! p @",
  "input": ["k", "2", "3"]
}

### Get processor-outs
GET http://localhost:59239/api/v1/processor-outs?request-id=11
username: admin
authorities: ROLE_ADMIN

### Get user
GET http://localhost:55068/api/v1/users/admin

### Get compiler-outs
GET http://localhost:54676/api/v1/compiler-outs
username: admin
authorities: ROLE_ADMIN

### Save user
PUT http://localhost:55068/api/v1/users
Content-Type: application/json

{
  "id": 1,
  "username": "admin",
  "password": "$2a$10$l/cgQsAHIKQiWp0TZN.C0OHNgPkPvlN6XS0K0aDxBXAxaLziavsqy",
  "roles": [
    {
      "id": 1,
      "name": "ROLE_ADMIN"
    }
  ],
  "requests": [
    {
      "id": 1,
      "text": "variable a\n3 a !\na @",
      "debug": true
    }
  ]
}

###
POST http://localhost:8765/file-service/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMjgzODYzMCwiZXhwIjoxNzAyODQwMDcwfQ.bPaT19fFqL4g59TzviHqjV7CiIIRLPAabHlw6e5NWMI

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testProg.txt"
Content-Type: text/plain

variable a
3 a !
a @

###
GET http://localhost:8765/file-service/files/info/2
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyciIsImlhdCI6MTcwMjE0NTc5MiwiZXhwIjoxNzAyMTQ3MjMyfQ.3kBhioUXjQxifLqlkDCyJIWbr11fDbV8PfOdgUOUbfA