### SignIn as vip (should be ok)
POST http://localhost:8765/auth/signIn
Content-Type: application/json

{
  "username": "vipvip",
  "password": "V1p-----"
}

### SignIn as user (should be ok)
POST http://localhost:8765/auth/signIn
Content-Type: application/json

{
  "username": "userr",
  "password": "Us3r----"
}

### SignIn as admin (should be ok)
POST http://localhost:8765/auth/signIn
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### ZorthCompile with expired JWT (should fail)
POST http://localhost:8765/zorth/compile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDQ4NDAwNSwiZXhwIjoxNzAwNDg1NDQ1fQ.mtVikKsE_3Sl3FF0JNOvaiV4lAvHco3qkhytexUi6Dw

{
  "debug": true,
  "text": "variable p\n3 p\n! p @"
}

### ZorthCompile with valid JWT (should be ok)
POST http://localhost:8765/zorth/compile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyciIsImlhdCI6MTcwMDY2MDY3OCwiZXhwIjoxNzAwNjYyMTE4fQ.uDePe3rv8i0yMlzBFimDtR1oIO10SZbG6Iad5QKSiOg

{
  "debug": true,
  "text": "variable p\n5 p\n! p @"
}

### Get compiler-outs (should be ok)
GET http://localhost:8765/zorth/compiler-outs
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDY2MTMzNCwiZXhwIjoxNzAwNjYyNzc0fQ.YIQEo8LUDahRmC0FJIRZthkN3d-Tjgb7QyiVMITTCrc

### Get debug-messages (should be ok)
GET http://localhost:8765/zorth/debug-messages?request-id=1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDY2MTMzNCwiZXhwIjoxNzAwNjYyNzc0fQ.YIQEo8LUDahRmC0FJIRZthkN3d-Tjgb7QyiVMITTCrc


### AddUser as user (should fail)
POST http://localhost:8765/user/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTY5OTczNTQ2NywiZXhwIjoxNjk5NzM2OTA3fQ.zHs2yJJPupxaQ3KcDnyN_Obviz9znuHxKPP5ajNFKA4
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### AddUser as admin (should be ok)
POST http://localhost:8765/user-service/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDY2MDY0NiwiZXhwIjoxNzAwNjYyMDg2fQ._jaCOiG8bUyeESzH4_0q8OEH15gzjT9TP_uwx843sKs

{
  "username": "userr",
  "password": "Us3r----"
}

### AddUser (should fail)
POST http://localhost:8765/user/api/v1/add
Content-Type: application/json
username: admin
authorities: ROLE_ADMIN

{
  "username": "adminnn",
  "password": "Adm1n---"
}

### ChangeRole as admin (should be ok)
PUT http://localhost:8765/user-service/users/userr/roles
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlhdCI6MTcwMDQ5MDg5OCwiZXhwIjoxNzAwNDkyMzM4fQ.g-4t4ej6v-WP6wsPrUeIfayx9xzEpmRERcOf-bB4bF0"

{
  "role": "ROLE_USER"
}

### Get requests of self as vip (should be ok)
GET http://localhost:8765/user-service/users/vipvip/requests
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ2aXB2aXAiLCJpYXQiOjE3MDAzMzQyOTMsImV4cCI6MTcwMDMzNTczM30._EDt9RjC7aO7wpoGgtcPDjRvzlv9CGxHPKfnh1I4Lw0

### Execute
POST http://localhost:52968/api/v1/execute
Content-Type: application/json
username: userr
authorities: ROLE_ADMIN

{
  "input": ["k", "2", "3"],
  "requestId": 3
}

### Pipeline
POST http://localhost:52968/api/v1/pipeline
Content-Type: application/json
username: admin
authorities: ROLE_ADMIN

{
  "debug": true,
  "text": "variable p\n5 p\n! p @",
  "input": ["k", "2", "3"]
}

### Get processor-outs
GET http://localhost:52968/api/v1/processor-outs?request-id=5
username: userr
authorities: ROLE_USER