version: '3.9'

services:

  postgres:
    hostname: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: db-highload
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: highload
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - rdb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      args:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
    ports:
      - "25565:25565"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-highload
      - SPRING_DATASOURCE_USERNAME=user_db
      - SPRING_DATASOURCE_PASSWORD=highload
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=TRUE
    restart: always
    depends_on:
      - postgres

volumes:
  rdb-data: