create table processor_out
(
    id              bigint generated by default as identity
        constraint "processor_outPK"
            primary key,
    input           oid,
    tick_logs       oid not null,
    compiler_out_id bigint
);