server:
  port: 8080
  error:
    include-message: always
spring:
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: user_db
    password: highload
    url: jdbc:postgresql://localhost:5432/db-highload
    driver-class-name: org.postgresql.Driver
  docker:
    compose:
      enabled: false
      file: dev-compose.yaml
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/master-changelog.xml
    default-schema: public

token:
  expire: 24
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
admin:
  username: admin
  password: admin
