server:
  port: 8765
  error:
    include-message: always
    whitelabel:
      enabled: false
  servlet:
    context-path: /api/v1

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - StripPrefix=1
        - RewritePath=/(?<path>.*), ${server.servlet.context-path}/$\{path}
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/signIn
        - id: add-user
          uri: lb://user
          predicates:
            - Path=/user-service/users
            - Method=POST
          filters:
            - AuthenticationFilter
        - id: user
          uri: lb://user
          predicates:
            - Path=/user-service/users/*/requests,/user-service/users/*/roles
          filters:
            - AuthenticationFilter
        - id: translator
          uri: lb://zorth-translator
          predicates:
            - Path=/zorth/compile,/zorth/compiler-outs/*,/zorth/debug-messages/*
          filters:
            - AuthenticationFilter
        - id: highload
          uri: lb://highload
          predicates:
            - Path=/highload/zorth/compile
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}