server:
  port: 0
  error:
    include-message: always
  servlet:
    context-path: /api/v1
spring:
  application:
    name: user-service
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: user_db
    password: highload
    url: jdbc:postgresql://localhost:5432/db-highload
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Europe/Moscow
  web:
    locale: en_US
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}
admin:
  username: admin
  password: admin