server:
  port: 0
  error:
    include-message: always
  servlet:
    context-path: /api/v1

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_URI:http://localhost:29092}
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: yarusking67@gmail.com
    password: obgv pxxy lcxh awlf

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}