server:
  port: 0
  error:
    include-message: always

ws-server: ws://localhost:6666/highload-ws
destination-topic: /topic/requests
subscribe-topic: /queue/responses

spring:
  webflux:
    base-path: /api/v1
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME:user_db}
    password: ${SPRING_DATASOURCE_PASSWORD:highload}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db-highload}
    driver-class-name: org.postgresql.Driver
  jackson:
    time-zone: Europe/Moscow
  web:
    locale: en_US
  cloud:
    loadbalancer:
      cache:
        enabled: false

eureka:
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${random.value}

reactive:
  feign:
    circuit:
      breaker:
        enabled: false