name: deploy
on:
  push:
    branches: ['master']

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test with Maven
        run: mvn test

  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on Odin via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout master
            git pull
            mvn clean install -DskipTests
            docker compose up -d
